name: Attendance Request
description: Request to be a proud member of Webducks clan!
title: "Add me to the clan"
labels: ["bug", "triage"]
assignees:
  - eymeen
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: work-experience
    attributes:
      label: How many years of professional work experience do you have?
      description: Please enter the number of years of work experience.
      placeholder: Enter your work experience in years
    validations:
      required: true

  - type: textarea
    id: additional-messages
    attributes:
      label: Any other messages (optional)
      description: Feel free to add any additional messages or comments.
      placeholder: Share any additional information.
    validations:
      required: false

   - type: checkboxes
    id: programming-languages
    attributes:
      label: Select languages you know:
      description: Please select the programming languages you know.
      options:
        - JavaScript
        - Python
        - C
        - PHP
        - SQL
        - Scala
    validations:
      required: true
