name: Attendance Request
description: Request to join the Webducks clan and get read/write access to all private/public sources!
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - eymeen
body:
  
