name: Attendance Request
description: Request to be a proud member of Webducks clan!
title: "Add me to the clan"
assignees:
  - eymeen
labels: "clan attendance"
body:
  - type: markdown
    attributes:
      value: |
        Request to join Webducks clan and get access to all private and public repositories, collab with clan members, ask members for help on your projects and help them with their projects, prized code battles and tournaments and more...

  - type: input
    id: working-role
    attributes: 
      label: Working Role
      description: what is your role/field
      placeholder: ex. MEVN full-stack web developer/Scala backend engineer
    validations:
      required: true

  - type: input
    id: coding-experience
    attributes:
      label: rate your problem-solving skills
      description: Please enter the honest number YOU rate yourself.
      placeholder: ex. 7
    validations:
      required: true
      type: integer
      min: 1
      max: 10

  - type: input
    id: coding-experience-otherskills
    attributes:
      label: rate your scripting, algorithms and data structures skills
      description: Please enter the honest number YOU rate yourself.
      placeholder: ex. 7
    validations:
      required: true
      type: integer
      min: 1
      max: 10

  - type: input
    id: years-of-coding-experience
    attributes:
      label: How many years of professional coding experience do you have?
      description: Please enter the number of years you have been coding.
      placeholder: Enter your coding experience in years
    validations:
      required: true
      type: integer

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Anything we can get in touch with you on
      placeholder: ex. email@example.com
    validations:
      required: true

  - type: textarea
    id: additional-messages
    attributes:
      label: Any other messages (optional)
      description: Feel free to add any additional messages or comments.
      placeholder: Share any additional information.
    validations:
      required: false
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
  # - type: checkboxes
  #   id: languages
  #   attributes:
  #     label: "Select the languages you're comfortable with"
  #     options:
  #       - label: JavaScript
  #         value: javascript
  #       - label: Python
  #         value: python
  #       - label: PHP
  #         value: php
  #       - label: C
  #         value: c
  #       - label: C#
  #         value: csharp
  #       - label: C++
  #         value: cpp
  #       - label: SQL 
  #         value: sql
  #       - label: Scala
  #         value: scala
  #       - label: Java
  #         value: java
  #       - label: Go
  #         value: go
  #   validations:
  #     required: true
